Repository EnergyTajo/EnergyTajo-FE, pull requests merged in 2024-10, with the labels that each got.

#6 깃 충돌 파일 해결
  package-lock.json
  package.json
  public/img/qrcode.png
  public/index.html
  src/App.js
  src/MainPage.css
  src/MainPage.js
  src/NavigationBar.css
  src/NavigationBar.js
  src/index.css
  src/index.js
Labels: fix

#9 Feature/8 main page
  src/MainPage.js
Labels: features

#12 Feature/10 main page add
  .eslintrc.js
  .prettierrc
  package-lock.json
  package.json
  public/img/logo.png
  public/img/mainPageHeader.png
  public/img/map.png
  public/img/qrcode.png
  public/index.html
  src/App.js
  src/MainPage.css
  src/MainPage.js
  src/NavigationBar.css
  src/NavigationBar.js
  src/index.js
  src/main/EnergyDetail.js
  src/main/MainPage.css
  src/main/MainPage.js
  src/main/Menu.css
  src/main/Menu.js
  src/main/MyPage.css
  src/main/MyPage.js
  src/main/Nav.css
  src/main/Nav.js
  src/main/PointConversion1.js
Labels: features

#14 ✨ Feat : 포인트 전환 페이지 완료
  src/App.js
  src/PointConversion/PointConversion.css
  src/PointConversion/PointConversion1.js
  src/PointConversion/PointConversion2.js
  src/UsingBycycle/UsingBycycle.css
  src/UsingBycycle/UsingBycycle.js
  src/main/PointConversion1.js
Labels: features

#16 📁 File : 파일 정리 (세부 내용은 이슈 확인)
  src/App.js
  src/plus/EnergyDetail.js
  src/plus/MyPage.css
  src/plus/MyPage.js
Labels: features

#24 ✨ Feat : 자전거 이용을 위한 Map 기능
  package-lock.json
  package.json
  public/img/map_marker.png
  public/index.html
  src/App.js
  src/FindBicycle/FindBicycle.css
  src/FindBicycle/FindBicycle.js
  src/UsingBicycle/QRScannerPage.js
  src/UsingBicycle/UsageHistory.js
  src/UsingBicycle/UsingBicycle.css
  src/UsingBicycle/UsingBicycle.js
  src/main/MainPage.js
Labels: features

#26 Feature/25-css-modify
  src/FindBicycle/FindBicycle.css
  src/PointConversion/PointConversion.css
  src/UsingBicycle/UsingBicycle.css
  src/main/MainPage.css
  src/main/Menu.css
Labels: features

#28 🎨 Design : css 재수정
  src/PointConversion/PointConversion.css
  src/UsingBicycle/UsingBicycle.css
Labels: fix

#32 🎨 Design : css 재수정3
  src/PointConversion/PointConversion.css
  src/UsingBicycle/UsingBicycle.css
Labels: fix

#34 🎨 Design : 마지막으로 css 수정
  src/PointConversion/PointConversion.css
Labels: fix

#36 🎨 Design : 포인트 전환 페이지 CSS 수정
  src/PointConversion/PointConversion.css
Labels: fix

#38 🎨 Design : 포인트 전환 페이지 CSS 수정 (span)
  src/PointConversion/PointConversion.css
  src/PointConversion/PointConversion2.js
Labels: fix

#42 🔨 Fix : 포인트 전환 페이지2 수정
  src/PointConversion/PointConversion.css
  src/PointConversion/PointConversion2.js
Labels: fix

#44 🔨 Fix : 포인트 전환 페이지2 문제 해결
  src/PointConversion/PointConversion.css
Labels: fix

#46 🔨 Fix : 포인트 교환 페이지2 CSS 완전 수정 - 완료
  src/PointConversion/PointConversion.css
  src/PointConversion/PointConversion2.js
Labels: fix

#48 Feature/47 energy detail page
  src/App.js
  src/ConnectCard/ConnectCard.css
  src/ConnectCard/ConnectCard.js
  src/EnergyDetail/EnergyDetail.css
  src/EnergyDetail/EnergyDetail.js
  src/MyPage/MyPage.css
  src/MyPage/MyPage.js
  src/UsingBicycle/UsageHistory.js
  src/plus/EnergyDetail.js
Labels: features

#50 Feature/49 connect card page
  .eslintrc.js
  package-lock.json
  package.json
  src/App.js
  src/ConnectCard/CardCheck.js
  src/ConnectCard/ConnectCard.css
  src/ConnectCard/ConnectCard.js
  src/main/Menu.js
Labels: features

#52 🎨 Design : ConnectCard 카드 등록 페이지 CSS 수정
  src/ConnectCard/ConnectCard.css
  src/ConnectCard/ConnectCard.js
Labels: fix

#53 회원가입 및 로그인 js
  package-lock.json
  package.json
  src/App.js
  src/Join/JoinPage.css
  src/Join/JoinPage.js
  src/Login/LoginPage.css
  src/Login/LoginPage.js
Labels: features

#56 Feature/55 로그인 및 회원가입 api 연결
  public/img/sns_google.png
  public/img/sns_kakao.png
  public/img/sns_naver.png
  src/Join/JoinPage.js
  src/Login/LoginPage.css
  src/Login/LoginPage.js
Labels: features

#61 Feature/59 join api
  package-lock.json
  package.json
  public/img/favicon.ico
  public/index.html
  src/Join/JoinPage.css
  src/Join/JoinPage.js
  src/Login/LoginPage.css
  src/Login/LoginPage.js
Labels: features, fix

#63 Feature/62 login fix
  src/Join/JoinPage.css
  src/Join/JoinPage.js
  src/Login/LoginPage.css
Labels: fix

#67 ✨ Feat : mainpage api 연결
  src/UsingBicycle/UsingBicycle.css
  src/main/MainPage.css
  src/main/MainPage.js
Labels: features

#69 ✨ Feat : 사용자 이름 반환 및 로그아웃 api 연결
  package-lock.json
  package.json
  src/main/Menu.js
Labels: features

#71 ✨ Feat : 이용 내역 api 연결 및 css 수정
  src/EnergyDetail/EnergyDetail.css
  src/EnergyDetail/EnergyDetail.js
Labels: features

#73 Feature/72 point api
  package-lock.json
  package.json
  src/EnergyDetail/EnergyDetail.css
  src/PointConversion/PointConversion.css
  src/PointConversion/PointConversion1.css
  src/PointConversion/PointConversion1.js
  src/PointConversion/PointConversion2.js
Labels: features, fix

#75 ✨ Feat : api 연결 및 테스트를 위해 푸시
  .env
  package-lock.json
  package.json
  src/UsingBicycle/QRScannerPage.js
  src/UsingBicycle/UsageHistory.js
  src/UsingBicycle/UsingBicycle.js
Labels: features

#77 Feature/76 qr fix
  public/img/profile.png
  src/App.js
  src/UsingBicycle/QRScannerPage.js
  src/UsingBicycle/UsageHistory.js
  src/UsingBicycle/UsingBicycle.css
  src/UsingBicycle/UsingBicycle.js
Labels: features
